//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessPoliza
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionPoliza
    {
        public int idAsignacionPoliza { get; set; }
        public int idCliente { get; set; }
        public int idPoliza { get; set; }
        public int idEstadoPoliza { get; set; }
        public System.DateTime fechaAsignacion { get; set; }
        public System.DateTime fechaCancelacion { get; set; }
        public string idUsuario { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual EstadoPoliza EstadoPoliza { get; set; }
        public virtual Poliza Poliza { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
