//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessPoliza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poliza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poliza()
        {
            this.AsignacionPoliza = new HashSet<AsignacionPoliza>();
        }
    
        public int idPoliza { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int idTipoCubrimiento { get; set; }
        public System.DateTime inicioVigencia { get; set; }
        public int periodoCobertura { get; set; }
        public decimal precio { get; set; }
        public int idTipoRiesgo { get; set; }
        public string idUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionPoliza> AsignacionPoliza { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual TipoCubrimiento TipoCubrimiento { get; set; }
        public virtual TipoRiesgo TipoRiesgo { get; set; }
    }
}
